# DATA details
spring:
   datasource:
      username: xxxxx
      password: xxxxx
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:xe

   jpa:
      show-sql: true
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl       

# PORT details
server.port: 9999
